# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17q-x9Qo9Z3Twd143jJtrngCXTCq1J_XE
"""

# ==============================================================
# Synthetic Heart Rate Dataset Generator for Triage Scenarios
# Author: Lee, C.C. (2025)
# Based on: Ullah et al. (2013) - "Towards automated self-tagging in emergency health cases"
# ==============================================================
# Generates: 1000 virtual patient records with triage tags (START system)
# Output: synthetic_hr_triage_dataset.csv
# ==============================================================

import numpy as np
import pandas as pd

# -----------------------------
# Stage 1: Configuration
# -----------------------------
np.random.seed(42)       # Ensures reproducibility
n_patients = 1000        # Total number of synthetic patients

# -----------------------------
# Stage 2: Generate Heart Rate Data by Triage Category
# -----------------------------
# START triage guideline–based HR distribution
red_hr = np.random.normal(loc=145, scale=10, size=200)     # Immediate (critical)
yellow_hr = np.random.normal(loc=120, scale=5, size=250)   # Delayed (serious)
green_hr = np.random.normal(loc=85, scale=10, size=400)    # Minor (stable)
black_hr = np.random.normal(loc=25, scale=5, size=150)     # Deceased (no pulse)

# Combine all HR values into one array
heart_rates = np.concatenate([red_hr, yellow_hr, green_hr, black_hr])

# Assign triage labels
labels = (['Immediate'] * 200 +
          ['Delayed'] * 250 +
          ['Minor'] * 400 +
          ['Deceased'] * 150)

# Build initial DataFrame
synthetic_df = pd.DataFrame({
    'Patient_ID': range(1, n_patients + 1),
    'Heart_Rate_bpm': heart_rates,
    'Triage_Level': labels
})

# -----------------------------
# Stage 3: Add Noise and Variability (for Realism)
# -----------------------------
# Simulate sensor noise (±3 bpm Gaussian)
synthetic_df['Heart_Rate_bpm'] += np.random.normal(0, 3, n_patients)

# Clip HR values within physiological range (20–200 bpm)
synthetic_df['Heart_Rate_bpm'] = synthetic_df['Heart_Rate_bpm'].clip(20, 200)

# Add timestamp for temporal realism (1 reading per second)
synthetic_df['Timestamp'] = pd.date_range(start='2025-01-01', periods=n_patients, freq='s')

# -----------------------------
# Stage 4: Export Dataset
# -----------------------------
output_file = "synthetic_hr_triage_dataset.csv"
synthetic_df.to_csv(output_file, index=False)

print("✅ Synthetic dataset generated successfully!")
print(f"📁 File saved as: {output_file}")
print("\nDataset Summary:")
print(synthetic_df.head())

# Optional: quick statistics
print("\n--- Basic Statistics ---")
print(synthetic_df.groupby('Triage_Level')['Heart_Rate_bpm'].describe())

